audio:
  sample_rate: 16000
  silence_th_db: 30 # ~0.00065 rms
  silence_win_s: 0.5

featurizer:
  hop_len_ms: 15
  win_len_ms: 30
  f_min: 60
  f_max: 8000
  n_mels: 60
  n_mfcc: 12
  cache_enabled: false
  cache_dir: data/features/cache/
  cache_expire_hours: 24
  cache_max_size: 10

diarization:
  cache_enabled: false
  cache_dir: data/diarization/cache/
  cache_expire_hours: 24
  cache_max_size: 10

  # Params in hf/pyannote/speaker-diarization/config.yaml
  seg_model: "pyannote/segmentation@2022.07"
  emb_model: "speechbrain/spkrec-ecapa-voxceleb"
  clustering_algorithm: "AgglomerativeClustering"
  embedding_exclude_overlap: true
  clustering_method: "centroid"
  clustering_min_size: 15
  clustering_threshold: 0.7153814381597874
  segmentation_min_duration_off: 0.5817029604921046
  segmentation_threshold: 0.4442333667381752

xgboost:
  context_window: 10
  gamma: 0
  max_depth: 6

lstm:
  hidden_dim: 64
  num_layers: 2
  batch_size: 64
  frames_per_sample: 64  # stft windows per lstm sample
  frames_label: 64
  predict_hop_frames: 16

outputs:
  video_width: 1280
  segment_length: 30
  density_window_s: 30
  smooth_win_s: 1.5
  color_style: dark

styles:
  dark:
    style_mpl: dark_background
    wv_signal: [242, 149, 0]
    label_colors:
      default: [100, 100, 100]
      p: [100, 100, 255] # light-blue
      l: [143, 0, 255] # violet
      a: [255, 80, 80] # red
      b: [255, 187, 150] # orange
      g: [255, 150, 220] # pinkish
      m: [255, 238, 150] # yellowish
      c: [188, 255, 0] # lime green
      r: [180, 180, 180] # light-grey
      s: [220, 220, 220] # lighter-grey
      d: [120, 120, 120] # darker-grey
      n: [100, 100, 100] # Null label
      "-": [100, 100, 100] # Null label
  light:
    wv_signal: [242, 149, 0] # check
    label_colors:
      default: [100, 100, 100]
      p: [0, 0, 255] # blue
      l: [143, 0, 255] # violet
      a: [245, 150, 70] # orange
      b: [245, 150, 115] # lighter orange
      g: [255, 150, 220] # pinkish
      m: [116, 152, 92] # green
      c: [80, 100, 66] # darker green
      r: [80, 80, 80] # dark-grey
      s: [100, 100, 100] # light-grey
      o: [200, 200, 0] # yellow
      d: [130, 130, 130] # lighter-grey
      n: [150, 150, 150] # very light
      "-": [150, 150, 150] # same as n
